import type { Client, Task, Lead, Activity, CalendarEvent, DashboardStats } from '@/types'

export const MOCK_STATS: DashboardStats = {
  activeClients: 12,
  activeClientsGrowth: 8,
  monthlyRevenue: 24500,
  monthlyRevenueARS: 24500,
  monthlyRevenueUSD: 0,
  monthlyRevenueGrowth: 12,
  pendingTasks: 34,
  criticalTasks: 3,
  activeLeads: 8,
  leadsValue: 47000,
  leadsValueGrowth: 22,
  upcomingEvents: 5,
  tasksCompletedThisWeek: 18,
  newClientsThisMonth: 2,
}

export const MOCK_CLIENTS: Client[] = [
  {
    id: '1',
    name: 'Sofia Martín',
    company: 'Bloom Skincare',
    email: 'sofia@bloomskincare.com',
    phone: '+1 555 001',
    website: 'bloomskincare.com',
    status: 'active',
    services: ['social_media', 'paid_ads', 'content'],
    monthlyValue: 3200,
    currency: 'USD',
    startDate: new Date('2024-01-15'),
    industry: 'Beauty',
    country: 'US',
    tags: ['beauty', 'ecommerce', 'priority'],
    contacts: [],
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2025-05-01'),
  },
  {
    id: '2',
    name: 'Marcos Rivera',
    company: 'TechForge SaaS',
    email: 'marcos@techforge.io',
    website: 'techforge.io',
    status: 'active',
    services: ['seo', 'content', 'strategy'],
    monthlyValue: 5500,
    currency: 'USD',
    startDate: new Date('2023-11-01'),
    industry: 'Technology',
    country: 'MX',
    tags: ['saas', 'b2b', 'high-value'],
    contacts: [],
    createdAt: new Date('2023-10-25'),
    updatedAt: new Date('2025-04-28'),
  },
  {
    id: '3',
    name: 'Ana Gutiérrez',
    company: 'Verdant Foods',
    email: 'ana@verdantfoods.com',
    status: 'active',
    services: ['social_media', 'email', 'branding'],
    monthlyValue: 2100,
    currency: 'USD',
    startDate: new Date('2024-06-01'),
    industry: 'Food & Beverage',
    country: 'CO',
    tags: ['food', 'sustainable'],
    contacts: [],
    createdAt: new Date('2024-05-20'),
    updatedAt: new Date('2025-05-05'),
  },
  {
    id: '4',
    name: 'Daniel Torres',
    company: 'Apex Fitness',
    email: 'daniel@apexfitness.com',
    status: 'active',
    services: ['paid_ads', 'social_media'],
    monthlyValue: 1800,
    currency: 'USD',
    startDate: new Date('2024-09-01'),
    industry: 'Health & Fitness',
    country: 'US',
    tags: ['fitness', 'b2c'],
    contacts: [],
    createdAt: new Date('2024-08-15'),
    updatedAt: new Date('2025-05-03'),
  },
  {
    id: '5',
    name: 'Valentina Cruz',
    company: 'Luxora Jewelry',
    email: 'val@luxorajewelry.com',
    status: 'inactive',
    services: ['branding', 'social_media'],
    monthlyValue: 0,
    currency: 'USD',
    startDate: new Date('2025-05-14'),
    industry: 'Luxury',
    country: 'AR',
    tags: ['luxury', 'ecommerce'],
    contacts: [],
    createdAt: new Date('2025-05-10'),
    updatedAt: new Date('2025-05-14'),
  },
]

export const MOCK_TASKS: Task[] = [
  {
    id: 't1',
    title: 'Design May content calendar — Bloom Skincare',
    status: 'in_progress',
    priority: 'high',
    dueDate: new Date('2025-05-16'),
    tags: ['content', 'design'],
    checklist: [
      { id: 'c1', label: 'Investigar tendencias', completed: true, order: 0 },
      { id: 'c2', label: 'Borrador del calendario', completed: true, order: 1 },
      { id: 'c3', label: 'Aprobación del cliente', completed: false, order: 2 },
    ],
    attachments: [],
    comments: [],
    createdById: 'u1',
    createdAt: new Date('2025-05-10'),
    updatedAt: new Date('2025-05-13'),
  },
  {
    id: 't2',
    title: 'Set up Google Ads campaign — TechForge',
    status: 'todo',
    priority: 'critical',
    dueDate: new Date('2025-05-15'),
    tags: ['ads', 'google'],
    checklist: [],
    attachments: [],
    comments: [],
    createdById: 'u1',
    createdAt: new Date('2025-05-12'),
    updatedAt: new Date('2025-05-12'),
  },
  {
    id: 't3',
    title: 'Monthly report — All clients',
    status: 'todo',
    priority: 'high',
    dueDate: new Date('2025-05-20'),
    tags: ['reporting'],
    checklist: [],
    attachments: [],
    comments: [],
    createdById: 'u1',
    createdAt: new Date('2025-05-12'),
    updatedAt: new Date('2025-05-12'),
  },
  {
    id: 't4',
    title: 'Onboarding call — Luxora Jewelry',
    status: 'todo',
    priority: 'medium',
    dueDate: new Date('2025-05-17'),
    tags: ['onboarding'],
    checklist: [],
    attachments: [],
    comments: [],
    createdById: 'u1',
    createdAt: new Date('2025-05-14'),
    updatedAt: new Date('2025-05-14'),
  },
  {
    id: 't5',
    title: 'SEO audit — Verdant Foods website',
    status: 'review',
    priority: 'medium',
    dueDate: new Date('2025-05-18'),
    tags: ['seo'],
    checklist: [],
    attachments: [],
    comments: [],
    createdById: 'u1',
    createdAt: new Date('2025-05-08'),
    updatedAt: new Date('2025-05-14'),
  },
]

export const MOCK_LEADS: Lead[] = [
  {
    id: 'l1',
    name: 'Roberto Díaz',
    company: 'NexoBank',
    email: 'roberto@nexobank.com',
    status: 'proposal',
    source: 'referral',
    priority: 'high',
    potentialValue: 8000,
    currency: 'USD',
    services: ['strategy', 'content', 'seo'],
    nextAction: 'Enviar propuesta',
    nextActionDate: new Date('2025-05-16'),
    tags: ['fintech', 'high-value'],
    createdAt: new Date('2025-05-05'),
    updatedAt: new Date('2025-05-13'),
  },
  {
    id: 'l2',
    name: 'Camila Reyes',
    company: 'EduPath Academy',
    email: 'camila@edupathacademy.com',
    status: 'qualified',
    source: 'inbound',
    priority: 'medium',
    potentialValue: 3500,
    currency: 'USD',
    services: ['social_media', 'content'],
    nextAction: 'Llamada de descubrimiento',
    nextActionDate: new Date('2025-05-15'),
    tags: ['edtech', 'saas'],
    createdAt: new Date('2025-05-08'),
    updatedAt: new Date('2025-05-12'),
  },
  {
    id: 'l3',
    name: 'Felipe Navarro',
    company: 'Summit Real Estate',
    email: 'fnavarro@summitrealty.com',
    status: 'contacted',
    source: 'social',
    priority: 'low',
    potentialValue: 2500,
    currency: 'USD',
    services: ['paid_ads', 'social_media'],
    tags: ['real-estate'],
    createdAt: new Date('2025-05-10'),
    updatedAt: new Date('2025-05-11'),
  },
]

export const MOCK_ACTIVITIES: Activity[] = [
  {
    id: 'a1',
    type: 'task_completed',
    title: 'Tarea completada',
    description: 'Facebook Ads creativo — Apex Fitness',
    userId: 'u1',
    createdAt: new Date(Date.now() - 1000 * 60 * 15),
  },
  {
    id: 'a2',
    type: 'lead_created',
    title: 'Nuevo lead agregado',
    description: 'Roberto Díaz · NexoBank',
    userId: 'u1',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 1.5),
  },
  {
    id: 'a3',
    type: 'payment_received',
    title: 'Pago recibido',
    description: '$3,200 · Bloom Skincare',
    userId: 'u1',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 5),
  },
  {
    id: 'a4',
    type: 'client_created',
    title: 'Nuevo cliente incorporado',
    description: 'Luxora Jewelry',
    userId: 'u1',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24),
  },
  {
    id: 'a5',
    type: 'task_created',
    title: 'Tarea creada',
    description: 'Reporte mensual para todos los clientes',
    userId: 'u1',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 26),
  },
]

export const MOCK_EVENTS: CalendarEvent[] = [
  {
    id: 'e1',
    title: 'Strategy call — Bloom Skincare',
    type: 'meeting',
    startDate: new Date(new Date().setHours(10, 0)),
    endDate: new Date(new Date().setHours(11, 0)),
    allDay: false,
    attendees: [],
    createdById: 'u1',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'e2',
    title: 'Proposal deadline — NexoBank',
    type: 'deadline',
    startDate: new Date(Date.now() + 1000 * 60 * 60 * 48),
    endDate: new Date(Date.now() + 1000 * 60 * 60 * 48),
    allDay: true,
    attendees: [],
    createdById: 'u1',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'e3',
    title: 'Onboarding — Luxora Jewelry',
    type: 'meeting',
    startDate: new Date(Date.now() + 1000 * 60 * 60 * 72),
    endDate: new Date(Date.now() + 1000 * 60 * 60 * 73),
    allDay: false,
    attendees: [],
    createdById: 'u1',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
]
